/// Flutter icons HudIconFont
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HudIconFont
///      fonts:
///       - asset: fonts/HudIconFont.ttf
///
/// 
///

library rt_progress_hud;

import 'package:flutter/widgets.dart';

class HudIconFont {
  HudIconFont._();

  static const _kFontFam = 'HudIconFont';

  static const IconData warn = const HudFontData(0xe805, fontFamily: _kFontFam);
  static const IconData success = const HudFontData(0xe806, fontFamily: _kFontFam);
  static const IconData fail = const HudFontData(0xe847, fontFamily: _kFontFam);
}


class HudFontData extends IconData {

  final String fontFamily;

  const HudFontData(int codePoint, {this.fontFamily}) : super(codePoint,fontFamily:HudIconFont._kFontFam,fontPackage:'rt_progress_hud');
}

