/// Flutter icons HudIconFont
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HudIconFont
///      fonts:
///       - asset: fonts/HudIconFont.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HudIconFont {
  HudIconFont._();

  static const _kFontFam = 'HudIconFont';

  static const IconData warn_1 = const IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData fail_1 = const IconData(0xe844, fontFamily: _kFontFam);
  static const IconData success_1 = const IconData(0xe84d, fontFamily: _kFontFam);
}
